const fs=require('node:fs'),path=require('node:path');const {connect}=require('./cdp.cjs');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let mode=process.argv[2],out=process.env.RECENCY_OUTPUT,r=JSON.parse(fs.readFileSync(path.join(out,mode+'-run.json'))),c=await connect(r.debug_port);if(!r.synthetic_only)throw Error('Synthetic fixture required');try{
 const ids=`[...document.querySelectorAll('[data-app-action-sidebar-thread-row]')].map(e=>e.getAttribute('data-app-action-sidebar-thread-id'))`;
 const before=await c.evaluate(ids);
 await c.evaluate(`window.__newChatEvents=[];window.addEventListener('message',e=>{let d=e.data;if(d?.type==='mcp-notification'&&['thread/started','turn/started','turn/completed'].includes(d.method))window.__newChatEvents.push({at:performance.now(),method:d.method,id:d.params.threadId||d.params.thread?.id})});(()=>{const b=[...document.querySelectorAll('button[aria-label]')].find(e=>/Project Alpha/.test(e.getAttribute('aria-label'))&&/开始新聊天|Start new chat|New chat/i.test(e.getAttribute('aria-label')));if(!b)throw Error('New project chat button missing');b.click();return true})()`);
 for(let i=0;i<100;i++){if(await c.evaluate(`!!document.querySelector('[contenteditable=true][role=textbox]')`))break;await sleep(200)}await sleep(1500);
 await c.evaluate(`document.querySelector('[contenteditable=true][role=textbox]').focus();true`);await c.call('Input.insertText',{text:'Synthetic new chat identity acceptance.'});await c.key('Enter','Enter',13);
 let start,rows,at;
 for(let i=0;i<160;i++){const events=await c.evaluate('window.__newChatEvents');const created=events.find(e=>e.method==='thread/started'&&!before.includes('local:'+e.id));start=created&&events.find(e=>e.method==='turn/started'&&e.id===created.id);rows=await c.evaluate(`([...document.querySelectorAll('[data-app-action-sidebar-thread-row]')].filter(e=>e.getAttribute('data-app-action-sidebar-thread-title')==='Synthetic new chat identity acceptance.').map(e=>e.getAttribute('data-app-action-sidebar-thread-id')))`);if(start&&rows.some(key=>!before.includes(key))){at=await c.evaluate('performance.now()');break}await sleep(100)}
 if(!start||!at||at-start.at>2000||new Set(rows.filter(x=>!before.includes(x))).size!==1)throw Error('Native new chat identity or order failed');
 for(let i=0;i<160;i++){if((await c.evaluate('window.__newChatEvents')).some(e=>e.method==='turn/completed'&&e.id===start.id))break;if(i===159)throw Error('New chat completion missing');await sleep(500)}
 const alias=rows.find(x=>!before.includes(x));const last=await c.evaluate(ids);if(!last.includes(alias))throw Error('New chat alias lost after completion');
 await c.evaluate(`(()=>{const row=document.querySelector('[data-app-action-sidebar-thread-id="${alias}"]');if(!row)throw Error('Native new chat row missing');const b=[...row.querySelectorAll('button')].find(e=>/^(Pin chat|置顶聊天)$/.test(e.getAttribute('aria-label')||''));if(!b)throw Error('Native pin action missing');b.click();return true})()`);await sleep(1000);
 if(!await c.evaluate(`!!document.querySelector('[data-app-action-sidebar-thread-id="${alias}"][data-app-action-sidebar-thread-pinned="true"]')`))throw Error('Native pin did not preserve alias');

 const sql="import sys,sqlite3;from pathlib import Path;d=sqlite3.connect((Path(sys.argv[1])/'state_5.sqlite').as_uri()+'?mode=ro',uri=True);assert d.execute('select thread_section_id from threads where id=?',(sys.argv[2],)).fetchone()==('01984de2-8f74-7c91-a3b2-5c5e937cf318',);d.close()";
 const check=require('node:child_process').spawnSync('py',['-3','-c',sql,r.home,start.id],{encoding:'utf8'});if(check.status!==0)throw Error('Physical pin identity check failed: '+check.stderr);
 fs.writeFileSync(path.join(out,mode+'-new-chat.json'),JSON.stringify({status:'passed',real_composer:true,real_project_new_chat:true,unique_row_preserved:true,native_pin:true,physical_pin_identity_verified:true,thread_id:start.id,sidebar_alias:alias,start_to_visible_ms:at-start.at},null,2));console.log('Real new-chat identity and unique sidebar row passed');
}finally{c.close()}})().catch(e=>{console.error(e);process.exit(1)});
