"""Execute the complete packaged row with retained memo and synthetic state."""
import json,subprocess
from frontend_feature_contracts import _extract_function,_with_module_stubs,ContractError
def run(initial,node='node'):
    funcs={n:_extract_function(initial.decode(),n) for n in ('TVs','F4','Vbs','qZp')}
    script='\n'.join(funcs.values())+SCENARIOS
    cp=subprocess.run([node,'-'],input=_with_module_stubs(script,funcs),text=True,capture_output=True,encoding='utf8',timeout=30)
    if cp.returncode:raise ContractError('Actual mounted row: '+cp.stderr[-2000:])
    return json.loads(cp.stdout)

SCENARIOS = "\nconst assert=(x,m)=>{if(!x)throw Error(m)};\nlet pending=null,unread=false,scalar=null,loading=false;\nconst rowMemo=new Array(200).fill(Symbol.for('react.memo_cache_sentinel'));\nconst DVs={c:()=>rowMemo},Ubs={c:()=>new Array(10).fill(Symbol.for('react.memo_cache_sentinel'))};\nconst jsx=(type,props)=>({type,props:props||{}}),j6={jsx,jsxs:jsx},I4={jsx,jsxs:jsx};\nconst Oo=()=>({formatMessage:m=>m.defaultMessage}),Ar=()=>({get:()=>null});\nconst He=(a)=>a===lE?{summary:{hasUnreadTurn:unread,threadSource:null},pendingRequest:pending,unreadMessageCount:0}:a===FWr?[]:a===HWr?scalar:a===BWr?(loading?'loading':'idle'):a===xBs?'Fixture':a===false?false:null;\nconst xVs=()=>({archived:false,usesExternalArchiveHandling:false}),Hzo=()=>false,yvn=()=>false,mBs=()=>false,fMn=()=>false,kp=()=>null;\nconst color=n=>{if(typeof n?.type==='function')n=n.type(n.props);return n?.props?.style?.background??null};\nconst run=(pin=false,active=false)=>TVs({conversationId:'fixture',hostId:'local',P:pin,isActive:active,disableHoverCard:true});\nlet row=run();assert(row?.props?.statusState,'actual row state reaches display');assert(color(F4({statusState:row.props.statusState}))===null,'idle');\npending={type:'implementPlan'};row=run();assert(row.props.statusState.p===true,'actual state pending source');assert(color(F4({statusState:row.props.statusState}))==='#eab308','actual route yellow');\nrow=run(true);assert(row.props.statusState.i===true&&color(F4({statusState:row.props.statusState}))==='#eab308','pinned plan remains yellow');\npending=null;unread=true;row=run(true);assert(color(F4({statusState:row.props.statusState}))==='var(--color-text-danger)','pinned unread red');\nrow=run(false,true);assert(color(F4({statusState:row.props.statusState}))==='var(--color-text-info)','selection does not impersonate pin');\nunread=false;scalar='implementPlan';row=run();assert(!row.props.statusState.p&&color(F4({statusState:row.props.statusState}))===null,'scalar does not impersonate pending request');\nloading=true;row=run();assert(row.props.statusState.type==='loading','loading retained');\nprocess.stdout.write(JSON.stringify({status:'passed',actual_row:true,retained_memo:true,pending_recompute:true,pinned_recompute:true,selection_independent:true,scalar_rejected:true}));\n"
